pessoa = ('\n\t    Luis Gusstavo Fé Varella     ')
print (pessoa)
print ('Exemplo com lstrip : {}'.format(pessoa.lstrip()))
print ('Exemplo com rstrip: {}'.format(pessoa.rstrip()))
print ('Exemplo com strip:{}'.format(pessoa.strip()))