nome=input('Qual é o seu nome? ')
print('É um prazer te conhecer, {}' .format(nome))
idade=input('Qual a sua idade? ')
peso=input('Qual é o seu peso? ')
print('nome:{}'.format(nome),'idade:{}'.format(idade),'peso:{}'.format(peso))