num1=int(input('Digite um número: '))
num2=int(input('Digite outro número: '))
soma=(num1+num2)
print(type(num1))
print(type(num2))
print('A soma entre {}'.format(num1), 'e {}'.format(num2), 'é {}'.format(soma))
print('A soma entre {} e {} é {}'.format(num1,num2,soma))
